// Code generated by entc, DO NOT EDIT.

package droom

const (
	// Label holds the string label denoting the droom type in the database.
	Label = "droom"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIsGameRunning holds the string denoting the is_game_running field in the database.
	FieldIsGameRunning = "is_game_running"
	// FieldPanel holds the string denoting the panel field in the database.
	FieldPanel = "panel"
	// FieldUpUserID holds the string denoting the up_user_id field in the database.
	FieldUpUserID = "up_user_id"
	// FieldDownUserID holds the string denoting the down_user_id field in the database.
	FieldDownUserID = "down_user_id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// Table holds the table name of the droom in the database.
	Table = "drooms"
)

// Columns holds all SQL columns for droom fields.
var Columns = []string{
	FieldID,
	FieldIsGameRunning,
	FieldPanel,
	FieldUpUserID,
	FieldDownUserID,
	FieldCreateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsGameRunning holds the default value on creation for the "is_game_running" field.
	DefaultIsGameRunning bool
	// DefaultPanel holds the default value on creation for the "panel" field.
	DefaultPanel string
	// DefaultUpUserID holds the default value on creation for the "up_user_id" field.
	DefaultUpUserID string
	// DefaultDownUserID holds the default value on creation for the "down_user_id" field.
	DefaultDownUserID string
)
