// Code generated by entc, DO NOT EDIT.

package dchessdbcache

const (
	// Label holds the string label denoting the dchessdbcache type in the database.
	Label = "dchessdb_cache"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBoard holds the string denoting the board field in the database.
	FieldBoard = "board"
	// FieldResp holds the string denoting the resp field in the database.
	FieldResp = "resp"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// Table holds the table name of the dchessdbcache in the database.
	Table = "dchessdb_caches"
)

// Columns holds all SQL columns for dchessdbcache fields.
var Columns = []string{
	FieldID,
	FieldBoard,
	FieldResp,
	FieldCreateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
