// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DusersColumns holds the columns for the "dusers" table.
	DusersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString},
	}
	// DusersTable holds the schema information for the "dusers" table.
	DusersTable = &schema.Table{
		Name:       "dusers",
		Columns:    DusersColumns,
		PrimaryKey: []*schema.Column{DusersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DusersTable,
	}
)

func init() {
}
