// Code generated by entc, DO NOT EDIT.

package dsession

const (
	// Label holds the string label denoting the dsession type in the database.
	Label = "dsession"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldRoomID holds the string denoting the room_id field in the database.
	FieldRoomID = "room_id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// Table holds the table name of the dsession in the database.
	Table = "dsessions"
)

// Columns holds all SQL columns for dsession fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldRoomID,
	FieldCreateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUserID holds the default value on creation for the "user_id" field.
	DefaultUserID string
	// DefaultRoomID holds the default value on creation for the "room_id" field.
	DefaultRoomID string
)
