// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/orestonce/ChessGame/ent/dchessdbcache"
	"github.com/orestonce/ChessGame/ent/predicate"
)

// DChessdbCacheUpdate is the builder for updating DChessdbCache entities.
type DChessdbCacheUpdate struct {
	config
	hooks    []Hook
	mutation *DChessdbCacheMutation
}

// Where appends a list predicates to the DChessdbCacheUpdate builder.
func (dcu *DChessdbCacheUpdate) Where(ps ...predicate.DChessdbCache) *DChessdbCacheUpdate {
	dcu.mutation.Where(ps...)
	return dcu
}

// SetBoard sets the "board" field.
func (dcu *DChessdbCacheUpdate) SetBoard(s string) *DChessdbCacheUpdate {
	dcu.mutation.SetBoard(s)
	return dcu
}

// SetResp sets the "resp" field.
func (dcu *DChessdbCacheUpdate) SetResp(b []byte) *DChessdbCacheUpdate {
	dcu.mutation.SetResp(b)
	return dcu
}

// SetCreateTime sets the "create_time" field.
func (dcu *DChessdbCacheUpdate) SetCreateTime(t time.Time) *DChessdbCacheUpdate {
	dcu.mutation.SetCreateTime(t)
	return dcu
}

// Mutation returns the DChessdbCacheMutation object of the builder.
func (dcu *DChessdbCacheUpdate) Mutation() *DChessdbCacheMutation {
	return dcu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (dcu *DChessdbCacheUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(dcu.hooks) == 0 {
		affected, err = dcu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DChessdbCacheMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dcu.mutation = mutation
			affected, err = dcu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(dcu.hooks) - 1; i >= 0; i-- {
			if dcu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dcu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dcu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (dcu *DChessdbCacheUpdate) SaveX(ctx context.Context) int {
	affected, err := dcu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dcu *DChessdbCacheUpdate) Exec(ctx context.Context) error {
	_, err := dcu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcu *DChessdbCacheUpdate) ExecX(ctx context.Context) {
	if err := dcu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (dcu *DChessdbCacheUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dchessdbcache.Table,
			Columns: dchessdbcache.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: dchessdbcache.FieldID,
			},
		},
	}
	if ps := dcu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dcu.mutation.Board(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: dchessdbcache.FieldBoard,
		})
	}
	if value, ok := dcu.mutation.Resp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: dchessdbcache.FieldResp,
		})
	}
	if value, ok := dcu.mutation.CreateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: dchessdbcache.FieldCreateTime,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, dcu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dchessdbcache.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// DChessdbCacheUpdateOne is the builder for updating a single DChessdbCache entity.
type DChessdbCacheUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DChessdbCacheMutation
}

// SetBoard sets the "board" field.
func (dcuo *DChessdbCacheUpdateOne) SetBoard(s string) *DChessdbCacheUpdateOne {
	dcuo.mutation.SetBoard(s)
	return dcuo
}

// SetResp sets the "resp" field.
func (dcuo *DChessdbCacheUpdateOne) SetResp(b []byte) *DChessdbCacheUpdateOne {
	dcuo.mutation.SetResp(b)
	return dcuo
}

// SetCreateTime sets the "create_time" field.
func (dcuo *DChessdbCacheUpdateOne) SetCreateTime(t time.Time) *DChessdbCacheUpdateOne {
	dcuo.mutation.SetCreateTime(t)
	return dcuo
}

// Mutation returns the DChessdbCacheMutation object of the builder.
func (dcuo *DChessdbCacheUpdateOne) Mutation() *DChessdbCacheMutation {
	return dcuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (dcuo *DChessdbCacheUpdateOne) Select(field string, fields ...string) *DChessdbCacheUpdateOne {
	dcuo.fields = append([]string{field}, fields...)
	return dcuo
}

// Save executes the query and returns the updated DChessdbCache entity.
func (dcuo *DChessdbCacheUpdateOne) Save(ctx context.Context) (*DChessdbCache, error) {
	var (
		err  error
		node *DChessdbCache
	)
	if len(dcuo.hooks) == 0 {
		node, err = dcuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DChessdbCacheMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dcuo.mutation = mutation
			node, err = dcuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(dcuo.hooks) - 1; i >= 0; i-- {
			if dcuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dcuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dcuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (dcuo *DChessdbCacheUpdateOne) SaveX(ctx context.Context) *DChessdbCache {
	node, err := dcuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (dcuo *DChessdbCacheUpdateOne) Exec(ctx context.Context) error {
	_, err := dcuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcuo *DChessdbCacheUpdateOne) ExecX(ctx context.Context) {
	if err := dcuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (dcuo *DChessdbCacheUpdateOne) sqlSave(ctx context.Context) (_node *DChessdbCache, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dchessdbcache.Table,
			Columns: dchessdbcache.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: dchessdbcache.FieldID,
			},
		},
	}
	id, ok := dcuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing DChessdbCache.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := dcuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dchessdbcache.FieldID)
		for _, f := range fields {
			if !dchessdbcache.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dchessdbcache.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := dcuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dcuo.mutation.Board(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: dchessdbcache.FieldBoard,
		})
	}
	if value, ok := dcuo.mutation.Resp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: dchessdbcache.FieldResp,
		})
	}
	if value, ok := dcuo.mutation.CreateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: dchessdbcache.FieldCreateTime,
		})
	}
	_node = &DChessdbCache{config: dcuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, dcuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dchessdbcache.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
