// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/orestonce/ChessGame/ent/dsession"
)

// DSession is the model entity for the DSession schema.
type DSession struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// RoomID holds the value of the "room_id" field.
	RoomID string `json:"room_id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DSession) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case dsession.FieldID, dsession.FieldUserID, dsession.FieldRoomID:
			values[i] = new(sql.NullString)
		case dsession.FieldCreateTime:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type DSession", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DSession fields.
func (d *DSession) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dsession.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				d.ID = value.String
			}
		case dsession.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				d.UserID = value.String
			}
		case dsession.FieldRoomID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field room_id", values[i])
			} else if value.Valid {
				d.RoomID = value.String
			}
		case dsession.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				d.CreateTime = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this DSession.
// Note that you need to call DSession.Unwrap() before calling this method if this DSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *DSession) Update() *DSessionUpdateOne {
	return (&DSessionClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the DSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *DSession) Unwrap() *DSession {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: DSession is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *DSession) String() string {
	var builder strings.Builder
	builder.WriteString("DSession(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteString(", user_id=")
	builder.WriteString(d.UserID)
	builder.WriteString(", room_id=")
	builder.WriteString(d.RoomID)
	builder.WriteString(", create_time=")
	builder.WriteString(d.CreateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DSessions is a parsable slice of DSession.
type DSessions []*DSession

func (d DSessions) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
